Feature/add get bill fn
leginote/assembly-ts pull request #12
Opened 2024-07-31 16:25 UTC by StatPan

lawmaker api 스타일과 비슷하게

getBillList 기능 구현해봤습니다

2024-08-01 00:56 UTC, sunrabbit123 commented
행동력 개쩌네요

2024-08-01 01:05 UTC, sunrabbit123 requested changes
오오오

2024-08-01 01:05 UTC, sunrabbit123 commented on src/constant/index.ts
> +  의결일: 'ResolutionDate',
파스칼 -> 카멜

2024-08-01 01:05 UTC, sunrabbit123 commented on src/constant/index.ts
> +  본회의심의결과: 'plenarysessionReviewResult',
```suggestion
  본회의심의결과: 'plenarySessionReviewResult',
```

2024-08-01 01:05 UTC, sunrabbit123 commented on src/constant/index.ts
> +  법사위처리일: 'lawProcessdate',
lawProcessDate의 경우 법 처리 일자 정도가 될 듯 한데
변수명 재정의 부탁드려요

2024-08-01 02:51 UTC, sunrabbit123 commented
related #8.

2024-08-01 06:07 UTC, StatPan commented on src/constant/index.ts
> +  법사위처리일: 'lawProcessdate',
법사위 이거 풀네임 갈까요? 변수명 길어져도?

2024-08-01 06:08 UTC, StatPan commented on src/constant/index.ts
> +  소관위: 'committee',
@sunrabbit123 
네네 변수명 길어져도, 풀네임으로 간다는 정책으로 가면 그게 맞을거 같아요

2024-08-01 06:08 UTC, StatPan commented on src/constant/index.ts
> +  위원회심사_처리일: 'committeeReviewProcessDate',
좋아요~!

2024-08-01 07:13 UTC, sunrabbit123 commented on src/constant/index.ts
> +  법사위처리일: 'lawProcessdate',
네네

2024-08-01 07:14 UTC, sunrabbit123 commented on src/constant/index.ts
> +  소관위: 'committee',
그 정책이 없다하더라도, 위원회 자체가 이미 committe라 별개로 선언해줘야한다고 봐요
기존 정의된 프로퍼티만 보더라도 committeeName이 있는데 얘가 위원회명이지 소관위이름은 아니거든요

2024-08-01 08:53 UTC, StatPan commented on src/constant/index.ts
> +  법사위처리일: 'lawProcessdate',
홈피에서 확인해봤는데 정식명칭이
법제사법위원회
LEGISLTION AND JUDICIARY COMMITTEE
그렇다면
LegislationAndJudiciaryCommittee

2024-08-01 08:59 UTC, StatPan commented on src/constant/index.ts
> +  소관위: 'committee',
jurisdiction
소관, 관할의 뜻

jurisdictionCommittee
소관위원회

2024-08-01 09:32 UTC, StatPan commented
@sunrabbit123 수정했는데 다시 한번 확인해보시죵
어우 익숙치 않은 영어

2024-08-01 09:35 UTC, sunrabbit123 commented
? 분신술인가

2024-08-01 09:44 UTC, StatPan commented
이전에 계정 만들었던게 있는데 삭제했는데 살아있어요 이상하게.. 로그인 안되는데
이메일 설정을 바꿨어요

2024-08-01 09:45 UTC, sunrabbit123 requested changes
추가로 plenarysessionReviewResult 얘 아직도 수정 안됐어영

2024-08-01 09:45 UTC, sunrabbit123 commented on src/bill/getBillList.ts
> +  const {
엇, 제가 작성했던거야 사용자들이 argument 이해하기 쉽게 변수명 transform해서 넣어놨던건데
이럴거면 굳이 구조분해할당이 필요없지않나 싶읍니다.

Argument 프로퍼티명을 수정해보는건 어떨까요

2024-08-01 09:45 UTC, sunrabbit123 commented on src/constant/index.ts
> + * @ignore `~처리`과 같은 이름을 지칭하는 변수의 경우 `Process`으로 끝나야함
굿

2024-08-01 09:45 UTC, sunrabbit123 commented on src/bill/index.spec.ts
> +describe('bill index.ts', () => {
엇 이게 필요한가요

2024-08-01 09:46 UTC, sunrabbit123 commented on src/bill/index.spec.ts
> +describe('bill index.ts', () => {
export, import 관련해서 vitest 테스트 커버리지 이슈라면 #15 에서 다루고 있습니다.

2024-08-01 10:02 UTC, StatPan commented on src/bill/index.spec.ts
> +describe('bill index.ts', () => {
테스트 과정에서 문제가 있어서 저걸로 풀기는 했는데, vitest에 정확한 이해도를 가지고 있진 않아요
요거 판단해주시믄 감사하겠습니닷

2024-08-02 00:43 UTC, sunrabbit123 commented on src/bill/index.spec.ts
> +describe('bill index.ts', () => {
삭제하고 함 돌려보죠
저도 이해도를 가지고 있진않은데 해결이 되고, 타 라이브러리들 참고했을 때 istanbul 사용하더라고요

2024-08-02 01:01 UTC, sunrabbit123 commented
그리고 작업 완료하시면 여기에 Re-request review 버튼 있어요
![image](https://github.com/user-attachments/assets/57e0eb46-c0fa-408b-9f99-8c6571c0612e)

2024-08-02 07:33 UTC, StatPan commented
오우 꿀팁 감사합니다
매번 골뱅이로 부를 뻔

2024-08-02 07:49 UTC, sunrabbit123 requested changes

2024-08-02 07:49 UTC, sunrabbit123 commented on src/bill/getBillList.ts
> +  BILL_ID?: string; // 의안ID, 예시: BILL_ID='PRC_Z2Z1Z0Z3X2L4M0H9A2V6K5R0V7P2H1'
argument 이름 통일하는게 좋을 듯 싶은데

여기처럼 Open API에 있는 인자값을 따라가는게 맞을까요
아니면 sdk기에 따로 변수를 convert하는편이 좋을까요?


저는 개인적으로 후자가 맞다고 봅니다. sdk기에

일단 이건 정해서 싹 수정하면 되는 내용이라 이야기만 하면 될 것 같아요

2024-08-02 08:10 UTC, StatPan commented on src/bill/getBillList.ts
> +  BILL_ID?: string; // 의안ID, 예시: BILL_ID='PRC_Z2Z1Z0Z3X2L4M0H9A2V6K5R0V7P2H1'
후자에 동의합니다
그렇게 하려고 하더라도 요청할 때 키값은 맞춰야 하니 정보 매핑해서 관리는 해야하는거죠?

2024-08-02 08:12 UTC, sunrabbit123 commented on src/bill/getBillList.ts
> +  BILL_ID?: string; // 의안ID, 예시: BILL_ID='PRC_Z2Z1Z0Z3X2L4M0H9A2V6K5R0V7P2H1'
네네 그래서 함수딴에서 구조분해할당으로 매핑하는 코드가 있는거고요

2024-08-02 13:35 UTC, StatPan commented
@sunrabbit123 
Argument 프로퍼티 이름 변경
객체구조 분해할당 제거
한번 확인해보실래요

2024-08-02 17:45 UTC, sunrabbit123 commented
음 기존 코드들도 해당 형태로 변환하도록 하죠 그럼

2024-08-02 17:45 UTC, sunrabbit123 approved these changes

2024-08-02 17:46 UTC, merged